apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: data-volume
        envFrom:
          - configMapRef:
              name: special-config
        envFrom:
          - secretRef:
              name: mysecret
      volumes:
      - name: data-volume
          persistentVolumeClaim:
            claimName: my-pvc
