apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: deploy-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-container
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: data-volume-api
        envFrom:
          - configMapRef:
              name: special-config
        envFrom:
          - secretRef:
              name: mysecret
      volumes:
      - name: data-volume-api
          persistentVolumeClaim:
            claimName: my-pvc-api
